package com.imageshack.constant;

public enum Models {
	ACTIVITIES_COUNT, ACTIVITIES, ACTIVITY, ALBUM, ALBUMS, AUTH, BASIC_IMAGE, COMMENT,
	COMMENTS, FOLLOWING_IMAGES, IMAGE, IMAGESHACK, IMAGES, LIKED_IMAGES, MINI_IMAGE,
	SIMPLE_ALBUM, SIMPLE_IMAGE, SIMPLE_IMAGES, SIMPLE, SIMPLE_USER, UPLOAD, USER,
	USER_SETTINGS, USERS, TAGS, REFERRAL_URL;
}

